# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'

- script: |
    sudo apt-add-repository ppa:qameta/allure
    sudo apt-get update
    sudo apt-get install allure
  displayName: Install allure

- script: |
  pip install --upgrade setuptools
  pip install -r requirements.txt
  pytest --alluredir=tmp/my_allure_results
  displayName: Install python requirements and run tests

- script: allure serve tmp/my_allure_results
  displayName: Get test results in HTML 
  
