# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    curl -o allure-2.7.0.tgz -Ls https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.tgz
    sudo tar -zxvf allure-2.7.0.tgz -C /opt/
    sudo ln -s /opt/allure-2.7.0/bin/allure /usr/bin/allure
    rm -rf allure-2.7.0.tgz
    allure --version
  displayName: Install Allure

- script: |
    cd docs
    echo "While I thought that I was learning how to live, I have been learning how to die." > quote1.txt
    cd ..
  displayName: Create file to write

- script: allure generate tmp/my_allure_results --clean -o docs
  displayName: Generate test report
  condition: always()

- script: |
    git config --global user.email "aigul.g.r@mail.ru"
    git config --global user.name "miaowization"
    git add docs
    git commit -m "updated allure report"
    git push https://$(username):$(password)@github.com/miaowization/takeAwayAssignment.git master
  condition: always()

- publish: $(System.DefaultWorkingDirectory)/docs
  artifact: .
