version: 2.1
jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run:
          name: "Switch to Python v3.7"
          command: |
            pyenv versions
            pyenv global 3.7.0
      - run:
          name: Install Google Chrome and chromedriver
          command: |
            wget -O google-chrome-latest.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-latest.deb
            wget https://chromedriver.storage.googleapis.com/85.0.4183.87/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/chromedriver
            sudo chown root:root /usr/bin/chromedriver
            sudo chmod +x /usr/bin/chromedriver

      - run:
          name: Install Firefox and geckodriver
          command: |
            sudo apt-add-repository ppa:qameta/allure
            sudo apt-get update
            sudo apt-get install firefox
            wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
            tar -xvzf geckodriver*
            sudo chmod +x geckodriver
            sudo mv geckodriver /usr/local/bin/
      - run:
          name: Install Allure
          command: |
            curl -o allure-2.7.0.tgz -Ls https://dl.bintray.com/qameta/generic/io/qameta/allure/allure/2.7.0/allure-2.7.0.tgz
            sudo tar -zxvf allure-2.7.0.tgz -C /opt/
            sudo ln -s /opt/allure-2.7.0/bin/allure /usr/bin/allure
            rm -rf allure-2.7.0.tgz
            allure --version
      - run:
          name: Install tools
          command: python -m pip install --upgrade pip setuptools wheel
      - run:
          name: Install requirements
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            pip install pytest
            pip install pytest-cov
            pytest tests --headless True --browser 'Firefox' --alluredir=tmp/my_allure_results
      - run:
          name: Generate test report
          command: allure generate tmp/my_allure_results
      - store_artifacts:
          path: ./allure-report